/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hbasesoft.actsports.portal.biz.vo;

public class Faq extends AbstractVo {

    /**
     * serialVersionUID <br>
     */
    private static final long serialVersionUID = 6515698045207443779L;

    private String faqId; // required

    private String question; // required

    private String url; // required

    public String getFaqId() {
        return faqId;
    }

    public void setFaqId(String faqId) {
        this.faqId = faqId;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
