/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hbasesoft.actsports.portal.biz.vo;


public class OptResp extends AbstractVo {

    /**
     * serialVersionUID <br>
     */
    private static final long serialVersionUID = -7958463797462098762L;

    public String resultCode; // required

    public String resultMsg; // optional

    public String getResultCode() {
        return resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    public String getResultMsg() {
        return resultMsg;
    }

    public void setResultMsg(String resultMsg) {
        this.resultMsg = resultMsg;
    }

}
