/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hbasesoft.actsports.portal.biz.vo;


public class WechatAccount extends AbstractVo {

    /**
     * serialVersionUID <br>
     */
    private static final long serialVersionUID = 4964446665498695020L;
    
    public static final String APPID = "appCode";

    public String appCode; // required

    public String appSecret; // required

    public String getAppCode() {
        return appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    public String getAppSecret() {
        return appSecret;
    }

    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

}
