/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-12-22 02:43:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ace_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1506577361980L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1494834924000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("webRoot");
      // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(basePath);
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title>");
      if (_jspx_meth_t_005fmutiLang_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"");
      if (_jspx_meth_t_005fmutiLang_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\t\t<meta name=\"description\" content=\"");
      if (_jspx_meth_t_005fmutiLang_005f2(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"plug-in/jquery/jquery.contextmenu.css\"/>\r\n");
      out.write("\t\t<!-- basic styles -->\r\n");
      out.write("\t\t<link href=\"plug-in/ace/assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if IE 7]>\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/font-awesome-ie7.min.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- page specific plugin styles -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- fonts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300\" />  -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace styles -->\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/ace.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/ace-skins.min.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"plug-in/ace/assets/css/ace-ie.min.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- inline styles related to this page -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace settings handler -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/ace-extra.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/respond.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"navbar navbar-default\" id=\"navbar\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttry{ace.settings.check('navbar' , 'fixed')}catch(e){}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-container\" id=\"navbar-container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header pull-left\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-leaf\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t管理平台\r\n");
      out.write("\t\t\t\t\t\t</small>\r\n");
      out.write("\t\t\t\t\t</a><!-- /.brand -->\r\n");
      out.write("\t\t\t\t</div><!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header pull-right\" role=\"navigation\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav ace-nav\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"grey\">\r\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-tasks\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-grey\">4</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-ok\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t还有4个任务完成\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">软件更新</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">65%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:65%\" class=\"progress-bar \"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">硬件更新</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">35%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:35%\" class=\"progress-bar progress-bar-danger\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">单元测试</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">15%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:15%\" class=\"progress-bar progress-bar-warning\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">错误修复</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:90%\" class=\"progress-bar progress-bar-success\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t查看任务详情\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"purple\">\r\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-bell-alt icon-animated-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-important\" id=\"noticeCount\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-header\" id=\"noticeTip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-warning-sign\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t0条公告\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar navbar-pink\" id=\"noticeContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- ajax加载 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"noticeContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:goAllNotice();\" id=\"noticeFooter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t查看全部\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"green\">\r\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-envelope icon-animated-vertical\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-success\" id=\"messageCount\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-header\" id=\"messageTip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-envelope-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t0条消息\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"messageContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:goAllMessage();\" id=\"messageFooter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t查看所有消息\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"light-blue\">\r\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"nav-user-photo\" src=\"plug-in/ace/avatars/avatar2.png\" alt=\"Jason's Photo\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"user-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small>\r\n");
      out.write("\t\t\t\t                    <span style=\"color: #666633\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roleName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-caret-down\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:add('");
      if (_jspx_meth_t_005fmutiLang_005f3(_jspx_page_context))
        return;
      out.write("','userController.do?changepassword','',550,200)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_t_005fmutiLang_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:openwindow('");
      if (_jspx_meth_t_005fmutiLang_005f5(_jspx_page_context))
        return;
      out.write("','userController.do?userinfo')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_t_005fmutiLang_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:openwindow('");
      if (_jspx_meth_t_005fmutiLang_005f7(_jspx_page_context))
        return;
      out.write("','tSSmsController.do?getSysInfos')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_t_005fmutiLang_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:add('");
      if (_jspx_meth_t_005fmutiLang_005f9(_jspx_page_context))
        return;
      out.write("','userController.do?changestyle','',550,250)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_t_005fmutiLang_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:clearLocalstorage()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_t_005fmutiLang_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:logout()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-off\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_t_005fmutiLang_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul><!-- /.ace-nav -->\r\n");
      out.write("\t\t\t\t</div><!-- /.navbar-header -->\r\n");
      out.write("\t\t\t</div><!-- /.container -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-container\" id=\"main-container\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttry{ace.settings.check('main-container' , 'fixed')}catch(e){}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-container-inner\">\r\n");
      out.write("\t\t\t\t<a class=\"menu-toggler\" id=\"menu-toggler\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<span class=\"menu-text\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\ttry{ace.settings.check('sidebar' , 'fixed')}catch(e){}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebar-shortcuts\" id=\"sidebar-shortcuts\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-shortcuts-large\" id=\"sidebar-shortcuts-large\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<button class=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-signal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-pencil\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-group\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-cogs\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>  -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-shortcuts-mini\" id=\"sidebar-shortcuts-mini\">\r\n");
      out.write("\t\t\t\t\t\t    <span class=\"btn btn-success\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-info\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-warning\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-danger\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div><!-- #sidebar-shortcuts -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-list\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a  href=\"javascript:addTabs({id:'home',title:'首页',close: false,url: 'loginController.do?acehome'});\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-dashboard\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-text\"> 首页 </span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_t_005fmenu_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul><!-- /.nav-list -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebar-collapse\" id=\"sidebar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-double-angle-left\" data-icon1=\"icon-double-angle-left\" data-icon2=\"icon-double-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\ttry{ace.settings.check('sidebar' , 'collapsed')}catch(e){}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12\" style=\"width: 99%;padding-left:2px;padding-right: 2px;\" id=\"tabs\">\r\n");
      out.write("\t                            <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t                                <!-- <li class=\"active\"><a href=\"#Index\" role=\"tab\" data-toggle=\"tab\">首页</a></li> -->\r\n");
      out.write("\t                            </ul>\r\n");
      out.write("\t                            <div class=\"tab-content\">\r\n");
      out.write("\t                                <div role=\"tabpanel\" class=\"tab-pane active\" id=\"Index\">\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- /.row -->\r\n");
      out.write("\t\t\t\t\t</div><!-- /.page-content -->\r\n");
      out.write("\t\t\t\t</div><!-- /.main-content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <div class=\"ace-settings-container\" id=\"ace-settings-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn btn-app btn-xs btn-warning ace-settings-btn\" id=\"ace-settings-btn\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-cog bigger-150\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"ace-settings-box\" id=\"ace-settings-box\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"skin-colorpicker\" class=\"hide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option data-skin=\"default\" value=\"#438EB9\">#438EB9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option data-skin=\"skin-1\" value=\"#222A2D\">#222A2D</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option data-skin=\"skin-2\" value=\"#C6487E\">#C6487E</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option data-skin=\"skin-3\" value=\"#D0D0D0\">#D0D0D0</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span>&nbsp; 选择皮肤</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-navbar\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"lbl\" for=\"ace-settings-navbar\"> 固定导航条</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-sidebar\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"lbl\" for=\"ace-settings-sidebar\"> 固定滑动条</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-breadcrumbs\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"lbl\" for=\"ace-settings-breadcrumbs\">固定面包屑</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-rtl\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"lbl\" for=\"ace-settings-rtl\">切换到左边</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"ace ace-checkbox-2\" id=\"ace-settings-add-container\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"lbl\" for=\"ace-settings-add-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t切换窄屏\r\n");
      out.write("\t\t\t\t\t\t\t\t<b></b>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>/#ace-settings-container -->\r\n");
      out.write("\t\t\t</div><!-- /.main-container-inner -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\r\n");
      out.write("\t\t\t\t<i class=\"icon-double-angle-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div><!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"changestylePanel\" style=\"display:none\" >\r\n");
      out.write("\t<form id=\"formobj\"  action=\"userController.do?savestyle\" name=\"formobj\" method=\"post\">\r\n");
      out.write("\t<table style=\"width: 550px\" cellpadding=\"0\" cellspacing=\"1\" class=\"formtable\">\r\n");
      out.write("\t\t<tr><td >风格</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input type=\"radio\" value=\"default\" name=\"indexStyle\" /> <span>经典风格</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input type=\"radio\" value=\"bootstrap\" name=\"indexStyle\" /> <span>BootStrap风格</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<!-- update-start--Author:gaofeng  Date:2014-01-10 for:新增首页风格  -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input type=\"radio\" value=\"shortcut\" name=\"indexStyle\" /> <span>ShortCut风格</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- update-start--Author:gaofeng  Date:2014-01-24 for:新增首页风格  -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input type=\"radio\" value=\"sliding\" name=\"indexStyle\"  /><span>Sliding云桌面</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- update-end--Author:longjb  Date:2013-03-15 for:新增首页风格  -->\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input type=\"radio\" value=\"ace\" name=\"indexStyle\"  /><span>ACE平面风格</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"changepassword\" style=\"display:none\">\r\n");
      out.write("\r\n");
      out.write("<input id=\"id\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<table style=\"width: 550px\" cellpadding=\"0\" cellspacing=\"1\" class=\"formtable\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\" width=\"20%\"><span class=\"filedzt\">原密码:</span></td>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input id=\"password\" type=\"password\" value=\"\" name=\"password\" class=\"inputxt\" datatype=\"*\" errormsg=\"请输入原密码\" /> <span class=\"Validform_checktip\"> 请输入原密码 </span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><span class=\"filedzt\">新密码:</span></td>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input  type=\"password\" value=\"\" name=\"newpassword\" class=\"inputxt\" plugin=\"passwordStrength\" datatype=\"*6-18\" errormsg=\"密码至少6个字符,最多18个字符！\" /> <span\r\n");
      out.write("\t\t\t\t\tclass=\"Validform_checktip\"> 密码至少6个字符,最多18个字符！ </span> <span class=\"passwordStrength\" style=\"display: none;\"> <b>密码强度：</b> <span>弱</span><span>中</span><span class=\"last\">强</span> </span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><span class=\"filedzt\">重复密码:</span></td>\r\n");
      out.write("\t\t\t\t<td class=\"value\"><input id=\"newpassword\" type=\"password\" recheck=\"newpassword\" datatype=\"*6-18\" errormsg=\"两次输入的密码不一致！\"> <span class=\"Validform_checktip\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.jQuery || document.write(\"<script src='plug-in/ace/assets/js/jquery-2.0.3.min.js'>\"+\"<\"+\"script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if IE]>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t window.jQuery || document.write(\"<script src='plug-in/ace/assets/js/jquery-1.10.2.min.js'>\"+\"<\"+\"script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif(\"ontouchend\" in document) document.write(\"<script src='plug-in/ace/assets/js/jquery.mobile.custom.min.js'>\"+\"<\"+\"script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/typeahead-bs2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- page specific plugin scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t  <script src=\"plug-in/ace/assets/js/excanvas.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/jquery.easy-pie-chart.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/flot/jquery.flot.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/flot/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/flot/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/ace/assets/js/ace.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<script src=\"plug-in/jquery-plugs/storage/jquery.storageapi.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"plug-in/ace/assets/js/bootstrap-tab.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/jquery/jquery.contextmenu.js\"></script>\r\n");
      out.write("\t\t<script src=\"plug-in/layer/layer.js\"></script>\r\n");
      out.write("\t    <script src=\"plug-in/ace/js/bootbox.js\"></script>\r\n");
      out.write("\t\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t//$( \"#tabs\" ).tabs();\r\n");
      out.write("\t\t\taddTabs({id:'home',title:'首页',close: false,url: 'loginController.do?acehome'});\r\n");
      out.write("\t\t\t$('.theme-poptit .close').click(function(){\r\n");
      out.write("\t    \t\t$('.theme-popover-mask').fadeOut(100);\r\n");
      out.write("\t    \t\t$('.theme-popover').slideUp(200);\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    \t$('#closeBtn').click(function(){\r\n");
      out.write("\t    \t\t$('.theme-popover-mask').fadeOut(100);\r\n");
      out.write("\t    \t\t$('.theme-popover').slideUp(200);\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    \t//$('#ace-settings-sidebar').click();\r\n");
      out.write("\t    \t//$('#sidebar').addClass('compact');\r\n");
      out.write("\t\t\t$('#sidebar li').addClass('hover').filter('.open').removeClass('open').find('> .submenu').css('display', 'none');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t\t$('.easy-pie-chart.percentage').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';\r\n");
      out.write("\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t$(this).easyPieChart({\r\n");
      out.write("\t\t\t\t\t\tbarColor: barColor,\r\n");
      out.write("\t\t\t\t\t\ttrackColor: trackColor,\r\n");
      out.write("\t\t\t\t\t\tscaleColor: false,\r\n");
      out.write("\t\t\t\t\t\tlineCap: 'butt',\r\n");
      out.write("\t\t\t\t\t\tlineWidth: parseInt(size/10),\r\n");
      out.write("\t\t\t\t\t\tanimate: /msie\\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,\r\n");
      out.write("\t\t\t\t\t\tsize: size\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.sparkline').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t$(this).sparkline('html', {tagValuesAttribute:'data-values', type: 'bar', barColor: barColor , chartRangeMin:$(this).data('min') || 0} );\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var placeholder = $('#piechart-placeholder').css({'width':'90%' , 'min-height':'150px'});\r\n");
      out.write("\t\t\t  var data = [\r\n");
      out.write("\t\t\t\t{ label: \"social networks\",  data: 38.7, color: \"#68BC31\"},\r\n");
      out.write("\t\t\t\t{ label: \"search engines\",  data: 24.5, color: \"#2091CF\"},\r\n");
      out.write("\t\t\t\t{ label: \"ad campaigns\",  data: 8.2, color: \"#AF4E96\"},\r\n");
      out.write("\t\t\t\t{ label: \"direct traffic\",  data: 18.6, color: \"#DA5430\"},\r\n");
      out.write("\t\t\t\t{ label: \"other\",  data: 10, color: \"#FEE074\"}\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t\t\t  function drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t \t  $.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tpie: {\r\n");
      out.write("\t\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt:0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight: {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity: 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke: {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor: '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth: 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle: 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend: {\r\n");
      out.write("\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\tposition: position || \"ne\", \r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor: null,\r\n");
      out.write("\t\t\t\t\t\tmargin:[-30,15]\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\t\tclickable: true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t drawPieChart(placeholder, data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t /**\r\n");
      out.write("\t\t\t we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\t so that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t placeholder.data('chart', data);\r\n");
      out.write("\t\t\t placeholder.data('draw', drawPieChart);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var $tooltip = $(\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\").hide().appendTo('body');\r\n");
      out.write("\t\t\t  var previousPoint = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  placeholder.on('plothover', function (event, pos, item) {\r\n");
      out.write("\t\t\t\tif(item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \" + item.series['percent']+'%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({top:pos.pageY + 10, left:pos.pageX + 10});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d1 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td1.push([i, Math.sin(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d2 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td2.push([i, Math.cos(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d3 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.2) {\r\n");
      out.write("\t\t\t\t\td3.push([i, Math.tan(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar sales_charts = $('#sales-charts').css({'width':'100%' , 'height':'220px'});\r\n");
      out.write("\t\t\t\t$.plot(\"#sales-charts\", [\r\n");
      out.write("\t\t\t\t\t{ label: \"Domains\", data: d1 },\r\n");
      out.write("\t\t\t\t\t{ label: \"Hosting\", data: d2 },\r\n");
      out.write("\t\t\t\t\t{ label: \"Services\", data: d3 }\r\n");
      out.write("\t\t\t\t], {\r\n");
      out.write("\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\tshadowSize: 0,\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tlines: { show: true },\r\n");
      out.write("\t\t\t\t\t\tpoints: { show: true }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txaxis: {\r\n");
      out.write("\t\t\t\t\t\ttickLength: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyaxis: {\r\n");
      out.write("\t\t\t\t\t\tticks: 10,\r\n");
      out.write("\t\t\t\t\t\tmin: -2,\r\n");
      out.write("\t\t\t\t\t\tmax: 2,\r\n");
      out.write("\t\t\t\t\t\ttickDecimals: 3\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\tbackgroundColor: { colors: [ \"#fff\", \"#fff\" ] },\r\n");
      out.write("\t\t\t\t\t\tborderWidth: 1,\r\n");
      out.write("\t\t\t\t\t\tborderColor:'#555'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#recent-box [data-rel=\"tooltip\"]').tooltip({placement: tooltip_placement});\r\n");
      out.write("\t\t\t\tfunction tooltip_placement(context, source) {\r\n");
      out.write("\t\t\t\t\tvar $source = $(source);\r\n");
      out.write("\t\t\t\t\tvar $parent = $source.closest('.tab-content')\r\n");
      out.write("\t\t\t\t\tvar off1 = $parent.offset();\r\n");
      out.write("\t\t\t\t\tvar w1 = $parent.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar off2 = $source.offset();\r\n");
      out.write("\t\t\t\t\tvar w2 = $source.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tif( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';\r\n");
      out.write("\t\t\t\t\treturn 'left';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.dialogs,.comments').slimScroll({\r\n");
      out.write("\t\t\t\t\theight: '300px'\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//Android's default browser somehow is confused when tapping on label which will lead to dragging the task\r\n");
      out.write("\t\t\t\t//so disable dragging when clicking on label\r\n");
      out.write("\t\t\t\tvar agent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t\t\t\tif(\"ontouchstart\" in document && /applewebkit/.test(agent) && /android/.test(agent))\r\n");
      out.write("\t\t\t\t  $('#tasks').on('touchstart', function(e){\r\n");
      out.write("\t\t\t\t\tvar li = $(e.target).closest('#tasks li');\r\n");
      out.write("\t\t\t\t\tif(li.length == 0)return;\r\n");
      out.write("\t\t\t\t\tvar label = li.find('label.inline').get(0);\r\n");
      out.write("\t\t\t\t\tif(label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation() ;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#tasks').sortable({\r\n");
      out.write("\t\t\t\t\topacity:0.8,\r\n");
      out.write("\t\t\t\t\trevert:true,\r\n");
      out.write("\t\t\t\t\tforceHelperSize:true,\r\n");
      out.write("\t\t\t\t\tplaceholder: 'draggable-placeholder',\r\n");
      out.write("\t\t\t\t\tforcePlaceholderSize:true,\r\n");
      out.write("\t\t\t\t\ttolerance:'pointer',\r\n");
      out.write("\t\t\t\t\tstop: function( event, ui ) {//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved\r\n");
      out.write("\t\t\t\t\t\t$(ui.item).css('z-index', 'auto');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click', function(){\r\n");
      out.write("\t\t\t\t\tif(this.checked) $(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\telse $(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tfunction loadModule(title,url,target){\r\n");
      out.write("\t\t\t//TODO addTab(title,url);\r\n");
      out.write("\t\t\t    $(\"#mainTitle\").text(title);\r\n");
      out.write("      \t\t\t$(\"#center\").attr(\"src\",url);\r\n");
      out.write("      \t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t  \tfunction logout(){\r\n");
      out.write("\t  \t\tbootbox.confirm(\"");
      if (_jspx_meth_t_005fmutiLang_005f13(_jspx_page_context))
        return;
      out.write("\", function(result) {\r\n");
      out.write("\t  \t\t\tif(result)\r\n");
      out.write("\t\t  \t\t\tlocation.href=\"loginController.do?logout\";\r\n");
      out.write("\t  \t\t});\r\n");
      out.write("  \t\t}\r\n");
      out.write("\t\tfunction opendialog(title,url,target){\r\n");
      out.write("\t\t\t//$(\"#dialog\").attr(\"src\",url);\r\n");
      out.write("\t\t\tbootbox.dialog({\r\n");
      out.write("\t\t\t\tmessage:$(\"#changestylePanel\").html(),\r\n");
      out.write("\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\tbuttons:{\r\n");
      out.write("\t\t\t\tOK:{\r\n");
      out.write("\t\t\t\tlabel: \"OK\", \r\n");
      out.write("\t\t\t\tcallback:function(){\r\n");
      out.write("\t\t\t\t\t    var indexStyle = $('input[name=\"indexStyle\"]:checked').val();\r\n");
      out.write("\t\t\t\t\t    if(indexStyle==undefined||indexStyle==\"\"){\r\n");
      out.write("\t\t\t\t\t    \tindexStyle = \"ace\";\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t    var cssTheme = $('input[name=\"cssTheme\"]:checked').val();\r\n");
      out.write("\t\t\t\t\t    if(cssTheme==undefined){\r\n");
      out.write("\t\t\t\t\t    \tcssTheme = \"\";\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\tvar form = $(\"#formobj\");//取iframe里的form\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t        \t\t\turl:form.attr('action'),\r\n");
      out.write("\t\t        \t\t\ttype:form.attr('method'),\r\n");
      out.write("\t\t        \t\t\tdata:\"indexStyle=\"+indexStyle,//+\"&cssTheme=\"+cssTheme,\r\n");
      out.write("\t\t        \t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar d = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tif (d.success) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar msg = d.msg;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbootbox.alert(msg);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbootbox.alert(d.msg);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t        \t\t\t},\r\n");
      out.write("\t\t        \t\t\terror:function(e){\r\n");
      out.write("\t\t        \t\t\t\tbootbox.alert(\"出错了哦\");\r\n");
      out.write("\t\t        \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t},Cancel: {label: \"CLOSE\", \r\n");
      out.write("\t\t\t\tcallback:function() {\r\n");
      out.write("\t\t\t\t\t\t//alert('close');//$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t}\r\n");
      out.write("\t\tfunction changepass(title,url,target){\r\n");
      out.write("\t\t\t//$(\"#dialog\").attr(\"src\",url);\r\n");
      out.write("\t\t\tbootbox.dialog({\r\n");
      out.write("\t\t\t\tmessage:'<form id=\"formobj2\"  action=\"userController.do?savenewpwd\" name=\"formobj2\" method=\"post\">'\r\n");
      out.write("\t\t\t\t\t+$(\"#changepassword\").html()+'</form>',\r\n");
      out.write("\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\tbuttons:{\r\n");
      out.write("\t\t\t\tOK:{\r\n");
      out.write("\t\t\t\tlabel: \"OK\", \r\n");
      out.write("\t\t\t\tcallback:function(){\r\n");
      out.write("\t\t\t\t\t//alert('not implement');\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t        \t\t\turl:\"userController.do?savenewpwd\",\r\n");
      out.write("\t\t        \t\t\ttype:\"post\",\r\n");
      out.write("\t\t        \t\t\tdata:$('#formobj2').serialize(),// 要提交的表单 ,\r\n");
      out.write("\t\t        \t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar d = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tif (d.success) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar msg = d.msg;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbootbox.alert(msg);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbootbox.alert(d.msg);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t        \t\t\t},\r\n");
      out.write("\t\t        \t\t\terror:function(e){\r\n");
      out.write("\t\t        \t\t\t\tbootbox.alert(\"出错了哦\");\r\n");
      out.write("\t\t        \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t},Cancel: {label: \"CLOSE\", \r\n");
      out.write("\t\t\t\tcallback:function() {\r\n");
      out.write("\t\t\t\t\t\talert('close');//$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t}\r\n");
      out.write("\t\tfunction profile(title,url,target){\r\n");
      out.write("\t\t\t//$(\"#dialog\").attr(\"src\",url);\r\n");
      out.write("\t\t\tbootbox.dialog({\r\n");
      out.write("\t\t\t\tmessage:'<iframe width=\"100%\" height=\"300px\" src=\"'+url+'\" style=\"border:1px #fff solid; background:#CCC;\"></iframe>',\r\n");
      out.write("\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\tbuttons:{\r\n");
      out.write("\t\t\t\tOK:{\r\n");
      out.write("\t\t\t\tlabel: \"OK\"},Cancel: {label: \"CLOSE\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t}\r\n");
      out.write("//update-begin--Author:张忠亮  Date:20150605 for：清除浏览器缓存\r\n");
      out.write("\t\t\tfunction clearLocalstorage(){\r\n");
      out.write("\t\t\t\tvar storage=$.localStorage;\r\n");
      out.write("\t\t\t\tif(!storage)\r\n");
      out.write("\t\t\t\t\tstorage=$.cookieStorage;\r\n");
      out.write("\t\t\t\tstorage.removeAll();\r\n");
      out.write("\t\t\t\t//bootbox.alert( \"浏览器缓存清除成功!\");\r\n");
      out.write("\t\t\t\talertTipTop(\"浏览器缓存清除成功!\",\"10%\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("//update-end--Author:张忠亮  Date:20150605 for：清除浏览器缓存\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//加载公告\r\n");
      out.write("\t\tvar url = \"noticeController.do?getNoticeList\";\r\n");
      out.write("\t\tjQuery.ajax({\r\n");
      out.write("    \t\turl:url,\r\n");
      out.write("    \t\ttype:\"GET\",\r\n");
      out.write("    \t\tdataType:\"JSON\",\r\n");
      out.write("    \t\tasync: false,\r\n");
      out.write("    \t\tsuccess:function(data){\r\n");
      out.write("    \t\t\tif(data.success){\r\n");
      out.write("    \t\t\t\tvar noticeList = data.attributes.noticeList;\r\n");
      out.write("    \t\t\t\tvar noticeCount = data.obj;\r\n");
      out.write("    \t\t\t\t//加载公告条数\r\n");
      out.write("    \t\t\t\tif(noticeCount>99){\r\n");
      out.write("    \t\t\t\t\t$(\"#noticeCount\").html(\"99+\");\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t$(\"#noticeCount\").html(noticeCount);\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t//加载公告提示\r\n");
      out.write("    \t\t\t\tvar noticeTip = \"\";\r\n");
      out.write("    \t\t\t\tnoticeTip += \"<i class='icon-warning-sign'></i>\";\r\n");
      out.write("    \t\t\t\tnoticeTip += noticeCount+\" \"+data.attributes.tip;\r\n");
      out.write("    \t\t\t\t$(\"#noticeTip\").html(noticeTip);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//加载公告条目\r\n");
      out.write("    \t\t\t\tvar noticeContent = \"\";\r\n");
      out.write("    \t\t\t\tif(noticeList.length > 0){\r\n");
      out.write("    \t\t\t\t\tfor(var i=0;i<noticeList.length;i++){\r\n");
      out.write("    \t\t\t\t\t\tnoticeContent +=\"<li><a href='javascript:goNotice(&quot;\"+noticeList[i].id+\"&quot;)' \";\r\n");
      out.write("    \t\t\t\t\t\tnoticeContent +=\"style='word-break:keep-all;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;'>\";\r\n");
      out.write("    \t\t\t\t\t\tnoticeContent +=\"<i class='btn btn-xs btn-primary fa fa-user'></i>\";\r\n");
      out.write("    \t\t\t\t\t\tnoticeContent +=\"&nbsp;\"+noticeList[i].noticeTitle + \"</a></li></ul></li>\";\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t$(\"#noticeContent\").html(noticeContent);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//加载公告底部文字\r\n");
      out.write("    \t\t\t\tvar noticeSeeAll = data.attributes.seeAll +\"<i class='ace-icon fa fa-arrow-right'></i>\";\r\n");
      out.write("    \t\t\t\t$(\"#noticeFooter\").html(noticeSeeAll);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//加载消息\r\n");
      out.write("\t\tvar url = \"tSSmsController.do?getMessageList\";\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("    \t\turl:url,\r\n");
      out.write("    \t\ttype:\"GET\",\r\n");
      out.write("    \t\tdataType:\"JSON\",\r\n");
      out.write("    \t\tasync: false,\r\n");
      out.write("    \t\tsuccess:function(data){\r\n");
      out.write("    \t\t\tif(data.success){\r\n");
      out.write("    \t\t\t\tvar messageList = data.attributes.messageList;\r\n");
      out.write("    \t\t\t\tvar messageCount = data.obj;\r\n");
      out.write("    \t\t\t\t//加载消息条数\r\n");
      out.write("    \t\t\t\tif(messageCount>99){\r\n");
      out.write("    \t\t\t\t\t$(\"#messageCount\").html(\"99+\");\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t$(\"#messageCount\").html(messageCount);\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t//加载消息tip提示\r\n");
      out.write("    \t\t\t\tvar messageTip = \"\";\r\n");
      out.write("\t\t\t\t\tmessageTip += \"<i class='ace-icon fa fa-envelope-o'></i>\";\r\n");
      out.write("\t\t\t\t\tmessageTip += messageCount+\" \"+data.attributes.tip;\r\n");
      out.write("    \t\t\t\t$(\"#messageTip\").html(messageTip);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//加载消息条目（有限）\r\n");
      out.write("    \t\t\t\tvar messageContent = \"\";\r\n");
      out.write("    \t\t\t\tif(messageList.length > 0){\r\n");
      out.write("    \t\t\t\t\tfor(var i=0;i<messageList.length;i++){\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<li><a href='javascript:goMessage(&quot;\"+messageList[i].id+\"&quot;)' class='clearfix'>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<img src='plug-in/ace/avatars/avatar3.png' class='msg-photo' alt='Alex’s Avatar' />\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<span class='msg-body'><span class='msg-title'>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<span class='blue'>\"+messageList[i].esSender+\":</span>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent += messageList[i].esTitle + \"</span>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<span class='msg-time'><i class='ace-icon fa fa-clock-o'></i><span>\"+messageList[i].esSendtimeTxt+\"</span></span>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"</span></a><input id='\"+messageList[i].id+\"_title' type='hidden' value='\"+messageList[i].esTitle+\"'>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<input id='\"+messageList[i].id+\"_status' type='hidden' value='\"+messageList[i].esStatus+\"'>\";\r\n");
      out.write("    \t\t\t\t\t\tmessageContent +=\"<input id='\"+messageList[i].id+\"_content' type='hidden' value='\"+messageList[i].esContent+\"'></li>\";\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t$(\"#messageContent\").html(messageContent);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//加载消息底部文字\r\n");
      out.write("    \t\t\t\tvar messageSeeAll = data.attributes.seeAll +\"<i class='ace-icon fa fa-arrow-right'></i>\";\r\n");
      out.write("    \t\t\t\t$(\"#messageFooter\").html(messageSeeAll);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("    function goAllNotice(){\r\n");
      out.write("    \tvar addurl = \"noticeController.do?noticeList\";\r\n");
      out.write("  \t\tcreatedetailwindow(\"公告\", addurl, 800, 400);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function goNotice(id){\r\n");
      out.write("  \t\tvar addurl = \"noticeController.do?goNotice&id=\"+id;\r\n");
      out.write("\t\tcreatedetailwindow(\"通知公告详情\", addurl, 750, 600);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function goAllMessage(){\r\n");
      out.write("    \tvar addurl = \"tSSmsController.do?getSysInfos\";\r\n");
      out.write("  \t\tcreatedetailwindow(\"消息\", addurl, 800, 400);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function goMessage(id){\r\n");
      out.write("    \tvar title = $(\"#\"+id+\"_title\").val();\r\n");
      out.write("    \tvar content = $(\"#\"+id+\"_content\").val();\r\n");
      out.write("    \t$(\"#msgId\").val(id);\r\n");
      out.write("    \t$(\"#msgTitle\").html(title);\r\n");
      out.write("    \t$(\"#msgContent\").html(content);\r\n");
      out.write("    \tvar status = $(\"#\"+id+\"_status\").val();\r\n");
      out.write("    \tif(status==1){\r\n");
      out.write("    \t\t$(\"#msgStatus\").html(\"未读\");\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$(\"#msgStatus\").html(\"已读\");\r\n");
      out.write("    \t}\r\n");
      out.write("\r\n");
      out.write("    \t$('.theme-popover-mask').fadeIn(100);\r\n");
      out.write("    \t$('.theme-popover').slideDown(200);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function readMessage(){\r\n");
      out.write("    \tvar msgId = $(\"#msgId\").val();\r\n");
      out.write("  \t\t  var url = \"tSSmsController.do?readMessage\";\r\n");
      out.write("  \t\t\t$.ajax({\r\n");
      out.write("  \t    \t\turl:url,\r\n");
      out.write("  \t    \t\ttype:\"GET\",\r\n");
      out.write("  \t    \t\tdataType:\"JSON\",\r\n");
      out.write("  \t    \t\tdata:{\r\n");
      out.write("  \t    \t\t\tmessageId:msgId\r\n");
      out.write("  \t    \t\t},\r\n");
      out.write("  \t    \t\tsuccess:function(data){\r\n");
      out.write("  \t    \t\t\tif(data.success){\r\n");
      out.write("  \t    \t\t\t\t$(\"#msgStatus\").html(\"已读\");\r\n");
      out.write("  \t    \t\t\t\t$(\"#\"+msgId+\"_status\").val('2');\r\n");
      out.write("  \t    \t\t\t}\r\n");
      out.write("  \t    \t\t}\r\n");
      out.write("  \t    \t});\r\n");
      out.write("    }\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fmutiLang_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f0 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f0.setParent(null);
    // /webpage/main/ace_main.jsp(7,9) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f0.setLangKey("jeect.platform");
    int _jspx_eval_t_005fmutiLang_005f0 = _jspx_th_t_005fmutiLang_005f0.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f1 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f1.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f1.setParent(null);
    // /webpage/main/ace_main.jsp(8,33) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f1.setLangKey("jeect.platform");
    int _jspx_eval_t_005fmutiLang_005f1 = _jspx_th_t_005fmutiLang_005f1.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f1);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f2 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f2.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f2.setParent(null);
    // /webpage/main/ace_main.jsp(9,36) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f2.setLangKey("jeect.platform");
    int _jspx_eval_t_005fmutiLang_005f2 = _jspx_th_t_005fmutiLang_005f2.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f2);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f3 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f3.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f3.setParent(null);
    // /webpage/main/ace_main.jsp(215,34) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f3.setLangKey("common.change.password");
    int _jspx_eval_t_005fmutiLang_005f3 = _jspx_th_t_005fmutiLang_005f3.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f3);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f4 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f4.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f4.setParent(null);
    // /webpage/main/ace_main.jsp(217,11) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f4.setLangKey("common.change.password");
    int _jspx_eval_t_005fmutiLang_005f4 = _jspx_th_t_005fmutiLang_005f4.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f4);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f5 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f5.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f5.setParent(null);
    // /webpage/main/ace_main.jsp(222,41) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f5.setLangKey("common.profile");
    int _jspx_eval_t_005fmutiLang_005f5 = _jspx_th_t_005fmutiLang_005f5.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f5);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f6 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f6.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f6.setParent(null);
    // /webpage/main/ace_main.jsp(224,11) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f6.setLangKey("common.profile");
    int _jspx_eval_t_005fmutiLang_005f6 = _jspx_th_t_005fmutiLang_005f6.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f6);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f7 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f7.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f7.setParent(null);
    // /webpage/main/ace_main.jsp(228,41) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f7.setLangKey("common.ssms.getSysInfos");
    int _jspx_eval_t_005fmutiLang_005f7 = _jspx_th_t_005fmutiLang_005f7.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f7);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f8 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f8.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f8.setParent(null);
    // /webpage/main/ace_main.jsp(230,11) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f8.setLangKey("common.ssms.getSysInfos");
    int _jspx_eval_t_005fmutiLang_005f8 = _jspx_th_t_005fmutiLang_005f8.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f8);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f9 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f9.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f9.setParent(null);
    // /webpage/main/ace_main.jsp(235,34) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f9.setLangKey("common.change.style");
    int _jspx_eval_t_005fmutiLang_005f9 = _jspx_th_t_005fmutiLang_005f9.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f9);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f10 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f10.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f10.setParent(null);
    // /webpage/main/ace_main.jsp(237,11) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f10.setLangKey("common.my.style");
    int _jspx_eval_t_005fmutiLang_005f10 = _jspx_th_t_005fmutiLang_005f10.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f10);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f11 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f11.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f11.setParent(null);
    // /webpage/main/ace_main.jsp(244,10) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f11.setLangKey("common.clear.localstorage");
    int _jspx_eval_t_005fmutiLang_005f11 = _jspx_th_t_005fmutiLang_005f11.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f11);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f12 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f12.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f12.setParent(null);
    // /webpage/main/ace_main.jsp(253,11) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f12.setLangKey("common.logout");
    int _jspx_eval_t_005fmutiLang_005f12 = _jspx_th_t_005fmutiLang_005f12.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f12);
    return false;
  }

  private boolean _jspx_meth_t_005fmenu_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:menu
    com.hbasesoft.framework.manager.tag.core.easyui.MenuTag _jspx_th_t_005fmenu_005f0 = (com.hbasesoft.framework.manager.tag.core.easyui.MenuTag) _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MenuTag.class);
    _jspx_th_t_005fmenu_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmenu_005f0.setParent(null);
    // /webpage/main/ace_main.jsp(315,6) name = style type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmenu_005f0.setStyle("ace");
    // /webpage/main/ace_main.jsp(315,6) name = menuFun type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmenu_005f0.setMenuFun((java.util.Map) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuMap}", java.util.Map.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_t_005fmenu_005f0 = _jspx_th_t_005fmenu_005f0.doStartTag();
    if (_jspx_th_t_005fmenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody.reuse(_jspx_th_t_005fmenu_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmenu_0026_005fstyle_005fmenuFun_005fnobody.reuse(_jspx_th_t_005fmenu_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    com.hbasesoft.framework.manager.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (com.hbasesoft.framework.manager.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.BaseTag.class);
    _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fbase_005f0.setParent(null);
    // /webpage/main/ace_main.jsp(484,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fbase_005f0.setType("tools");
    int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
    if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fmutiLang_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f13 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f13.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f13.setParent(null);
    // /webpage/main/ace_main.jsp(715,22) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f13.setLangKey("common.exit.confirm");
    int _jspx_eval_t_005fmutiLang_005f13 = _jspx_th_t_005fmutiLang_005f13.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f13);
    return false;
  }
}
