/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-12-22 02:42:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hbasesoft.framework.manager.core.util.SysThemesUtil;
import com.hbasesoft.framework.manager.core.enums.SysThemesEnum;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1506577361980L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1494834924000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("webRoot");
      // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(basePath);
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write('\r');
      out.write('\n');

  session.setAttribute("lang","zh-cn");
  SysThemesEnum sysTheme = SysThemesUtil.getSysTheme(request);
  String lhgdialogTheme = SysThemesUtil.getLhgdialogTheme(sysTheme);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <title>");
      if (_jspx_meth_t_005fmutiLang_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("  <!-- bootstrap & fontawesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/bootstrap.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/font-awesome.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"plug-in/accordion/css/accordion.css\">\r\n");
      out.write("  <!-- text fonts -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/ace-fonts.css\" />\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/jquery-ui.css\" />\r\n");
      out.write("  <!-- ace styles -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/ace.css\" class=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("  <!--[if lte IE 9]>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/ace-part2.css\" class=\"ace-main-stylesheet\" />\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("  <!--[if lte IE 9]>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plug-in/ace/css/ace-ie.css\" />\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("  <!-- ace settings handler -->\r\n");
      out.write("  <script src=\"plug-in/ace/js/ace-extra.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\r\n");
      out.write("  <!--[if lte IE 8]>\r\n");
      out.write("  <script src=\"plug-in/ace/js/html5shiv.js\"></script>\r\n");
      out.write("  <script src=\"plug-in/ace/js/respond.js\"></script>\r\n");
      out.write("  <![endif]-->\r\n");
      out.write(" <style>\r\n");
      out.write(" \t.light-login{\r\n");
      out.write(" \t\tbackground:#fff;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.row.bg-row{\r\n");
      out.write(" \t\tmargin-left:0;\r\n");
      out.write(" \t\tmargin-right:0;\r\n");
      out.write(" \t\tbackground:url(plug-in/ace/images/login_bg.png) no-repeat center;\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tleft:0;\r\n");
      out.write(" \t\ttop:50%;\r\n");
      out.write(" \t\twidth:100%;\r\n");
      out.write(" \t\theight:598px;\r\n");
      out.write(" \t\tmargin-top:-299px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout .main-content.new-container{\r\n");
      out.write(" \t\tpadding-left:0;\r\n");
      out.write(" \t\tpadding-right:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.col-sm-10.col-sm-offset-1.content-center{\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfloat:none;\r\n");
      out.write(" \t\r\n");
      out.write(" \t\theight:598px;\r\n");
      out.write(" \t\tpadding:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.col-sm-10.col-sm-offset-1{\r\n");
      out.write(" \t\tpadding:0;\r\n");
      out.write(" \t\tmax-width:1300px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.widget-box{\r\n");
      out.write(" \t\tmargin:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-container{\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tright:94px;\r\n");
      out.write(" \t\ttop:126px;\r\n");
      out.write(" \t\tbackground:#e8e9ee;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.alert-warning{\r\n");
      out.write(" \t\tbackground:none;\r\n");
      out.write(" \t\tborder:none;\r\n");
      out.write(" \t\tcolor:#ff9900;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t@media (min-width: 768px) {\r\n");
      out.write(" \t.col-sm-offset-1 {\r\n");
      out.write("    \tmargin-left: 16%;\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write(" \t.alert{\r\n");
      out.write(" \t\tpadding:0;\r\n");
      out.write(" \t\tmargin-bottom:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.header{\r\n");
      out.write(" \t\tmargin-top:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.light-login .widget-box{\r\n");
      out.write(" \t\tpadding:0;\r\n");
      out.write(" \t\t-webkit-box-shadow:none;\r\n");
      out.write(" \t\tbox-shadow:none;\r\n");
      out.write(" \t\tborder-bottom:none;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout .login-box .widget-main{\r\n");
      out.write(" \t\tpadding-bottom:0;\r\n");
      out.write(" \t\tbackground:#e8eaef;\r\n");
      out.write(" \t\tpadding:16px;\r\n");
      out.write(" \t\tpadding-bottom:4px\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout label{\r\n");
      out.write(" \t\tposition:relative;\r\n");
      out.write(" \t\tmargin-top:10px;\r\n");
      out.write(" \t\tmargin-bottom:15px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout label .input-icon img,.login-layout label .input-group>img{\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tleft:8px;\r\n");
      out.write(" \t\ttop:50%;\r\n");
      out.write(" \t\tz-index:20;\r\n");
      out.write(" \t\tmargin-top:-8px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout label .input-group>input{\r\n");
      out.write(" \t\theight:48px;\r\n");
      out.write(" \t\tpadding-left:25px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.input-icon.input-icon-right > input{\r\n");
      out.write(" \t\theight:48px;\r\n");
      out.write(" \t\tpadding-left:25px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.width-35{\r\n");
      out.write(" \t\twidth:100% !important\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.width-35.btn-primary{\r\n");
      out.write(" \t\tbackground-color:#ff9900 !important;\r\n");
      out.write(" \t\tborder-color:#ff9900;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.btn-sm{\r\n");
      out.write(" \t\tfont-size:22px;\r\n");
      out.write(" \t\tpadding:5px 9px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \tinput[type=\"text\"]{\r\n");
      out.write(" \t\tfont-size:14px !important;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout label+label+label{\r\n");
      out.write(" \t\tmargin-bottom:0;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.blue{\r\n");
      out.write(" \t\tcolor:#0a204c !important;\r\n");
      out.write(" \t}\r\n");
      out.write(" \th4.bigger{\r\n");
      out.write(" \t\tfont-size:18px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#header{\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tleft:0;\r\n");
      out.write(" \t\ttop:50%;\r\n");
      out.write(" \t\tmargin-top:-355px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#footer{\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tleft:0;\r\n");
      out.write(" \t\tbottom:50%;\r\n");
      out.write(" \t\tmargin-bottom:-370px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#header h3{\r\n");
      out.write(" \t\tcolor:#122752;\r\n");
      out.write(" \t\tfont-size:24px;\r\n");
      out.write(" \t\tposition:relative;\r\n");
      out.write(" \t\tpadding-left:16px;\r\n");
      out.write(" \t\tmargin-top:0;\r\n");
      out.write(" \t\tmargin-bottom:34px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#header h3:before{\r\n");
      out.write(" \t\tcontent:'';\r\n");
      out.write(" \t\tposition:absolute;\r\n");
      out.write(" \t\tleft:0;\r\n");
      out.write(" \t\ttop:50%;\r\n");
      out.write(" \t\theight:24px;\r\n");
      out.write(" \t\tmargin-top:-12px;\r\n");
      out.write(" \t\tbackground:#122752;\r\n");
      out.write(" \t\twidth:3px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#footer .logo{\r\n");
      out.write(" \t\twidth:200px;\r\n");
      out.write(" \t\tfloat:left;\r\n");
      out.write(" \t\tmargin-right:100px;\r\n");
      out.write(" \t\tline-height:43px;\r\n");
      out.write(" \t\tfont-size:28px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#footer .logo strong{\r\n");
      out.write(" \t\tfont-size:16px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#footer .copy{\r\n");
      out.write("\t\tline-height:43px;\r\n");
      out.write(" \t\ttext-align:center;\r\n");
      out.write(" \t\twidth:1200px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.login-layout .main-content.new-container{\r\n");
      out.write(" \t\tmin-height:728px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t@media(min-width: 710px){ #footer.inner-footer{\r\n");
      out.write(" \t\tdisplay:none\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login-layout light-login\">\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("  <div class=\"main-content new-container\">\r\n");
      out.write("  \t<div id='header' class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("  \t\t<h3>苏州市体育信息中心</h3>\r\n");
      out.write("  \t</div>\r\n");
      out.write("    <div class=\"row bg-row\">\r\n");
      out.write("      <div class=\"col-sm-10 col-sm-offset-1 content-center\">\r\n");
      out.write("        <div class=\"login-container\">\r\n");
      out.write("          <div class=\"position-relative\">\r\n");
      out.write("            <div id=\"login-box\" class=\"login-box visible widget-box no-border\">\r\n");
      out.write("              <div class=\"widget-body\">\r\n");
      out.write("                <form id=\"loinForm\" class=\"form-horizontal\"  check=\"loginController.do?checkuser\"  role=\"form\" action=\"loginController.do?login\"  method=\"post\">\r\n");
      out.write("                <div class=\"widget-main\">\r\n");
      out.write("                 <div class=\"alert alert-warning alert-dismissible\" role=\"alert\" id=\"errMsgContiner\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t  <div id=\"showErrMsg\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                  <h4 class=\"header blue lighter bigger\">\r\n");
      out.write("                \t    请输入账户信息\r\n");
      out.write("                  </h4>\r\n");
      out.write("\r\n");
      out.write("                      <label class=\"block clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"plug-in/ace/images/user_icon.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\"  name=\"userName\" class=\"form-control\" placeholder=\"请输入用户名\"  id=\"userName\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("                      </label>\r\n");
      out.write("                      <label class=\"block clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"plug-in/ace/images/lock_icon.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"请输入密码\" id=\"password\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("                      </label>\r\n");
      out.write("                      <label class=\"block clearfix\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <img src=\"plug-in/ace/images/confirm_icon.png\">\r\n");
      out.write("                          <input type=\"text\" style=\"float:left\" name=\"randCode\" class=\"form-control\" placeholder=\"请输入验证码\"  id=\"randCode\" />\r\n");
      out.write("                          <span class=\"input-group-addon\" style=\"padding: 0px;border:none;background:#e8e9ed;padding-left:15px;\"><img id=\"randCodeImage\" src=\"randCodeImage\"  /></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </label>\r\n");
      out.write("                      <div class=\"clearfix\">\r\n");
      out.write("                        <label class=\"inline\">\r\n");
      out.write("                          <input type=\"checkbox\" class=\"ace\" id=\"on_off\"  name=\"remember\" value=\"yes\"/>\r\n");
      out.write("                          <span class=\"lbl\">记住用户名</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <button type=\"button\" id=\"but_login\"  onclick=\"checkUser()\" class=\"width-35 pull-right btn btn-sm btn-primary\">\r\n");
      out.write("                          <span class=\"bigger-110\" >登录</span> \r\n");
      out.write("                        </button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"space-4\"></div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"center\"><h4 class=\"blue\" id=\"id-company-text\"></h4></div>\r\n");
      out.write("           \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id='footer' class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("        \t<div class=\"inner-footer\">\r\n");
      out.write("        \t\t<div class=\"logo\">\r\n");
      out.write("        \t\t\t<img src=\"plug-in/ace/images/logo.png\">\r\n");
      out.write("        \t\t\t<strong>苏州市体育信息中心</strong>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t\t<div class=\"copy\">\r\n");
      out.write("        \t\t\t<span>Copyright  ©  2016苏州市体育信息中心版权所有</span>  <span></span>\r\n");
      out.write("        \t\t\t<p></p>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"plug-in/ace/assets/js/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/jquery.ui.touch-punch.js\"></script>\r\n");
      out.write("<!-- ace scripts -->\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.scroller.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.colorpicker.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.fileinput.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.typeahead.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.wysiwyg.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.spinner.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.treeview.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.wizard.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/elements.aside.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.ajax-content.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.touch-drag.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.sidebar.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.sidebar-scroll-1.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.submenu-hover.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.widget-box.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.settings.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.settings-rtl.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.settings-skin.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.widget-on-reload.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/ace/ace.searchbox-autocomplete.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"plug-in/ace/js/bootbox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plug-in/login/js/login.js\"></script>\r\n");
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//update---start---author:jg_renjie at 20160410 for:#1038 【bug】新登录页面修改\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\toptErrMsg();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#errMsgContiner\").hide();\r\n");
      out.write("\tfunction optErrMsg(){\r\n");
      out.write("\t\t$(\"#showErrMsg\").html('');\r\n");
      out.write("\t\t$(\"#errMsgContiner\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("//update---end---author:jg_renjie at 20160410 for:#1038 【bug】新登录页面修改\t\r\n");
      out.write("\r\n");
      out.write(" //监听回车键登录\r\n");
      out.write("   $(document).keypress(function(e) { \r\n");
      out.write("    // 回车键事件 \r\n");
      out.write("       if(e.which == 13) { \r\n");
      out.write("    \t   checkUser();\r\n");
      out.write("       } \r\n");
      out.write("   });\r\n");
      out.write("\t\r\n");
      out.write("  //验证码输入框按下回车\r\n");
      out.write("   function randCodeKeyDown(){\r\n");
      out.write("\t  var lKeyCode = (navigator.appname==\"Netscape\")?event.which:window.event.keyCode; //event.keyCode按的建的代码，13表示回车\r\n");
      out.write("\t\tif(lKeyCode == 13){\r\n");
      out.write("\t\t\tcheckUser();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("  } \r\n");
      out.write("  //验证用户信息\r\n");
      out.write("  function checkUser(){\r\n");
      out.write("    if(!validForm()){\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    Login();\r\n");
      out.write("  }\r\n");
      out.write("  //表单验证\r\n");
      out.write("  function validForm(){\r\n");
      out.write("    if($.trim($(\"#userName\").val()).length==0){\r\n");
      out.write("      showErrorMsg(\"请输入用户名\");\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if($.trim($(\"#password\").val()).length==0){\r\n");
      out.write("      showErrorMsg(\"请输入密码\");\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if($.trim($(\"#randCode\").val()).length==0){\r\n");
      out.write("      showErrorMsg(\"请输入验证码\");\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  //登录处理函数\r\n");
      out.write("  function Login(orgId) {\r\n");
      out.write("    setCookie();\r\n");
      out.write("    var actionurl=$('form').attr('action');//提交路径\r\n");
      out.write("    var checkurl=$('form').attr('check');//验证路径\r\n");
      out.write("    var formData = new Object();\r\n");
      out.write("    var data=$(\":input\").each(function() {\r\n");
      out.write("      formData[this.name] =$(\"#\"+this.name ).val();\r\n");
      out.write("    });\r\n");
      out.write("    formData['orgId'] = orgId ? orgId : \"\";\r\n");
      out.write("    // update-begin--Author:ken  Date:20140629 for：添加语言选择\r\n");
      out.write("    formData['langCode']=$(\"#langCode\").val();\r\n");
      out.write("    // update-end--Author:ken  Date:20140629 for：添加语言选择\r\n");
      out.write("    formData['langCode'] = $(\"#langCode option:selected\").val();\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      async : false,\r\n");
      out.write("      cache : false,\r\n");
      out.write("      type : 'POST',\r\n");
      out.write("      url : checkurl,// 请求的action路径\r\n");
      out.write("      data : formData,\r\n");
      out.write("      error : function() {// 请求失败处理函数\r\n");
      out.write("      },\r\n");
      out.write("      success : function(data) {\r\n");
      out.write("        var d = $.parseJSON(data);\r\n");
      out.write("        if (d.success) {\r\n");
      out.write("          loginsuccess();\r\n");
      out.write("          var title, okButton;\r\n");
      out.write("          if($(\"#langCode\").val() == 'en') {\r\n");
      out.write("            title = \"Please select Org\";\r\n");
      out.write("            okButton = \"Ok\";\r\n");
      out.write("          } else {\r\n");
      out.write("            title = \"请选择组织机构\";\r\n");
      out.write("            okButton = \"确定\";\r\n");
      out.write("          }\r\n");
      out.write("          if (d.attributes.orgNum > 1) {\r\n");
      out.write("            $.dialog({\r\n");
      out.write("              id: 'LHG1976D',\r\n");
      out.write("              title: title,\r\n");
      out.write("              max: false,\r\n");
      out.write("              min: false,\r\n");
      out.write("              drag: false,\r\n");
      out.write("              resize: false,\r\n");
      out.write("              content: 'url:userController.do?userOrgSelect&userId=' + d.attributes.user.id,\r\n");
      out.write("              lock:true,\r\n");
      out.write("              button : [ {\r\n");
      out.write("                name : okButton,\r\n");
      out.write("                focus : true,\r\n");
      out.write("                callback : function() {\r\n");
      out.write("                  iframe = this.iframe.contentWindow;\r\n");
      out.write("                  var orgId = $('#orgId', iframe.document).val();\r\n");
      out.write("                  Login(orgId);\r\n");
      out.write("                  this.close();\r\n");
      out.write("                  return false;\r\n");
      out.write("                }\r\n");
      out.write("              }],\r\n");
      out.write("              close: function(){\r\n");
      out.write("                window.location.href = actionurl;\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            setTimeout(\"window.location.href='\"+actionurl+\"'\", 1000);\r\n");
      out.write("          }\r\n");
      out.write("       } else {\r\n");
      out.write("          showError\r\n");
      out.write("          if(d.msg == \"a\"){\r\n");
      out.write("            $.dialog.confirm(\"数据库无数据,是否初始化数据?\", function(){\r\n");
      out.write("              window.location = \"init.jsp\";\r\n");
      out.write("            }, function(){\r\n");
      out.write("            });\r\n");
      out.write("          } else\r\n");
      out.write("            showErrorMsg(d.msg);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("//update---start---author:jg_renjie at 20160410 for:#1038 【bug】新登录页面修改\r\n");
      out.write("  function showErrorMsg(msg){\r\n");
      out.write("    //tip(msg);\r\n");
      out.write("    $(\"#errMsgContiner\").show();\r\n");
      out.write("    $(\"#showErrMsg\").html(msg);\r\n");
      out.write("\treloadRandCodeImage();\r\n");
      out.write("    window.setTimeout(optErrMsg,3000); \r\n");
      out.write("  }\r\n");
      out.write("//update---end---author:jg_renjie at 20160410 for:#1038 【bug】新登录页面修改\r\n");
      out.write("  function darkStyle(){\r\n");
      out.write("    $('body').attr('class', 'login-layout');\r\n");
      out.write("    $('#id-text2').attr('class', 'red');\r\n");
      out.write("    $('#id-company-text').attr('class', 'blue');\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("  }\r\n");
      out.write("  function lightStyle(){\r\n");
      out.write("    $('body').attr('class', 'login-layout light-login');\r\n");
      out.write("    $('#id-text2').attr('class', 'grey');\r\n");
      out.write("    $('#id-company-text').attr('class', 'blue');\r\n");
      out.write("\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("  }\r\n");
      out.write("  function blurStyle(){\r\n");
      out.write("    $('body').attr('class', 'login-layout blur-login');\r\n");
      out.write("    $('#id-text2').attr('class', 'white');\r\n");
      out.write("    $('#id-company-text').attr('class', 'light-blue');\r\n");
      out.write("\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.print(lhgdialogTheme );
      out.write("\r\n");
      out.write("<!--  <span style= \"display:block;text-align:center\">版权说明：Copyright@2016 港华投资有限公司版权所有 | 名气家（深圳）信息服务有限公司设计研发</span>-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fmutiLang_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:mutiLang
    com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag _jspx_th_t_005fmutiLang_005f0 = (com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag) _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.MutiLangTag.class);
    _jspx_th_t_005fmutiLang_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmutiLang_005f0.setParent(null);
    // /webpage/login/login.jsp(14,9) name = langKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmutiLang_005f0.setLangKey("jeect.platform");
    int _jspx_eval_t_005fmutiLang_005f0 = _jspx_th_t_005fmutiLang_005f0.doStartTag();
    if (_jspx_th_t_005fmutiLang_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fmutiLang_0026_005flangKey_005fnobody.reuse(_jspx_th_t_005fmutiLang_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    com.hbasesoft.framework.manager.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (com.hbasesoft.framework.manager.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(com.hbasesoft.framework.manager.tag.core.easyui.BaseTag.class);
    _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fbase_005f0.setParent(null);
    // /webpage/login/login.jsp(315,0) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fbase_005f0.setType("tools");
    int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
    if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
    return false;
  }
}
